//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Participant
    {
        public int Id { get; set; }
        [Display(Name = "Contest")]
        public int Contest_Id { get; set; }
        [Display(Name = "User Email")]
        public string User_Id { get; set; }
        [Display(Name = "User Name")]
        public string User_Name { get; set; }
        [Display(Name = "Ingredients")]
        public string Ingredients { get; set; }
        [Display(Name = "Direction")]
        public string Description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Contest Contest { get; set; }
    }
}
