//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recipe
    {
        public int Recipe_Id { get; set; }
        [Display(Name = "Recipe")]
        public string Recipe_Name { get; set; }
        [Display(Name = "Direction")]
        public string Description { get; set; }
        [Display(Name = "Ingredients")]
        public string Ingredients { get; set; }
        [Display(Name = "User Role")]
        public string Label { get; set; }
        [Display(Name = "Posted By")]
        public string Posted_by { get; set; }
        [Display(Name = "Image")]
        public string Image { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
